import { StyleSheet, PixelRatio, Dimensions, Platform, StatusBar } from 'react-native';
import { getStatusBarHeight } from 'react-native-status-bar-height';
const {width, height} = Dimensions.get('window');
let screenWidth = Dimensions.get('window').width;

export default StyleSheet.create({
    Dkname:{
        flex:1,
        backgroundColor:'#F0F0F0'
    },
    Header_Dkname:{
        alignItems:'center',
    },
    aHeader_Dkname:{
        flex:2,
        paddingTop:20,
        position:'absolute',
        zIndex:1,
        flexDirection:'row',
    },
    Textheader_Dkname:{
        color:'#ffffff',
        fontWeight:'bold',
        fontSize:18,
    },
    IconLeft_Dkname:{
        flex:1,
        paddingLeft:10,
        fontSize:22,
        color:'#ffffff'
    },
    Container_Dkname:{
        alignItems:'center',
        backgroundColor:'#F0F0F0'
    },
    Text_Dkname:{
        alignItems:'center',
        flex:2,
        justifyContent:'center'
    },
    aText_Dkname:{
        marginBottom:10,
        fontWeight:'bold',
        color:'#111111',
        fontSize:16,
    },
    bText_Dkname:{
        color:'#111111',
        fontSize:14,
    },
    Import_Dkname:{
        paddingTop:10,
        flex:2
    },
    aImport_Dkname:{
        marginBottom:20,
        fontSize:16,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#ffffff',
        height:45,
        width:280,
        borderRadius:25,
    },
    bImport_Dkname:{
        fontSize:16,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#ffffff',
        height:45,
        width:280,
        borderRadius:25,
    },
    TextImport_Dkname:{
        paddingLeft:60,
        paddingRight:45,
        fontSize:16,
        color:'#111111'
    },
    IconButton_Dkname:{
        color:'#111111',
        fontSize:16
    },
    Button_Dkname:{
        justifyContent:'center',
        alignItems:'center',
        height:45,
        width:150,
        borderRadius:20,
        backgroundColor:'#F42535'
    },
    TextButton_Dkname:{
        fontSize:16,
        color:'#ffffff'
    },
    Img_Dkname:{
        width: width,
        height: width*429/720
    },
})